version: '3.9'

services:
  web:
    build: .
    volumes: 
      - .:/app
      - ./staticfiles:/app/staticfiles
   
    ports:
      - "8000:8000"
    container_name : web
    depends_on:
      - db
      - redis
    

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=goroute_pjt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
   

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:






