# Generated by Django 5.1.4 on 2025-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
