# Generated by Django 5.1.4 on 2025-01-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_normaluserprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busownermodel',
            name='user',
        ),
    ]
