# Generated by Django 5.1.4 on 2025-01-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_busownermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('distance_in_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_travel_time', models.DurationField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bus_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='admin_app.busownermodel')),
            ],
        ),
    ]
