# Generated by Django 5.1.4 on 2025-01-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_routemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemodel',
            name='estimated_travel_time',
        ),
        migrations.RemoveField(
            model_name='routemodel',
            name='fare',
        ),
    ]
