# Generated by Django 5.1.4 on 2025-01-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_routestopmodel_distance_in_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestopmodel',
            name='duration',
        ),
    ]
