# Generated by Django 5.1.4 on 2025-01-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_remove_routestopmodel_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ac', 'AC Bus'), ('sleeper_ac', 'Sleeper AC Bus'), ('non_ac_sleeper', 'Non-AC Sleeper'), ('semi_sleeper', 'Semi Sleeper')], max_length=100)),
                ('seat_type', models.CharField(choices=[('standard', 'Standard'), ('recliner', 'Recliner'), ('luxury', 'Luxury'), ('semi_sleeper', 'Semi Sleeper'), ('full_sleeper', 'Full Sleeper')], default='standard', max_length=50)),
                ('seat_count', models.IntegerField(choices=[(20, '20 Seats'), (30, '30 Seats'), (40, '40 Seats'), (50, '50 Seats'), (60, '60 Seats')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
