# Generated by Django 5.1.4 on 2025-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_busmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
