# Generated by Django 5.1.4 on 2025-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_busmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='bus_document',
            field=models.FileField(blank=True, null=True, upload_to='bus_documents/'),
        ),
    ]
