# Generated by Django 5.1.4 on 2025-01-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_busmodel_bus_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemodel',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
