# Generated by Django 5.1.4 on 2025-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_routemodel_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='Scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
