# Generated by Django 5.1.4 on 2025-01-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_scheduledbus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_order', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='admin_app.scheduledbus')),
            ],
        ),
    ]
