# Generated by Django 5.1.4 on 2025-01-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_scheduledstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
