# Generated by Django 5.1.4 on 2025-01-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_scheduledbus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledstop',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
