# Generated by Django 5.1.4 on 2025-01-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('related_data', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='admin_app.order')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='admin_app.seat')),
            ],
        ),
    ]
