# Generated by Django 5.1.4 on 2025-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='to_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
