# Generated by Django 5.1.4 on 2025-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='from_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='to_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
