# Generated by Django 5.1.4 on 2025-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_seat_date_seat_from_city_seat_to_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='busownermodel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='bus_owner_documents/'),
        ),
        migrations.AlterField(
            model_name='bustype',
            name='name',
            field=models.CharField(choices=[('ac', 'AC Bus'), ('non_ac', 'Non-AC Bus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bustype',
            name='seat_count',
            field=models.IntegerField(choices=[(20, '20 Seats'), (30, '30 Seats'), (40, '40 Seats')]),
        ),
        migrations.AlterField(
            model_name='bustype',
            name='seat_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury'), ('semi_sleeper', 'Semi Sleeper'), ('full_sleeper', 'Full Sleeper')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='issued', max_length=20),
        ),
    ]
