# Generated by Django 5.1.4 on 2025-01-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_busownermodel_document_alter_bustype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
