# Generated by Django 5.1.4 on 2025-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_seats',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
