# Generated by Django 5.1.4 on 2025-01-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0036_order_selected_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_seats',
        ),
    ]
