# Generated by Django 5.1.4 on 2025-01-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbus',
            name='bus_owner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
