# Generated by Django 5.1.4 on 2025-01-20 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_scheduledbus_bus_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('arrived', 'Arrived')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='admin_app.scheduledbus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='admin_app.scheduledstop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
