# Generated by Django 5.1.4 on 2025-01-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0042_stopstatusupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('bus_owner', 'Bus Owner'), ('normal_user', 'Normal User'), ('conductor', 'Conductor')], default='normal_user', max_length=20),
        ),
    ]
