# Generated by Django 5.1.4 on 2025-01-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0044_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='assigned_bus',
        ),
    ]
