# Generated by Django 5.1.4 on 2025-01-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0045_remove_conductor_assigned_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='travels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conductors', to='admin_app.busownermodel'),
            preserve_default=False,
        ),
    ]
