# Generated by Django 5.1.4 on 2025-01-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0046_conductor_travels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorScheduledBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(blank=True, null=True)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_buses', to='admin_app.conductor')),
                ('scheduled_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_schedules', to='admin_app.scheduledbus')),
            ],
        ),
    ]
