# Generated by Django 5.1.4 on 2025-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0047_conductorscheduledbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
