# Generated by Django 5.1.4 on 2025-01-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0049_conductor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductorscheduledbus',
            name='conductor',
        ),
    ]
