# Generated by Django 5.1.4 on 2025-01-20 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0050_remove_conductorscheduledbus_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorscheduledbus',
            name='conductor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_bus', to='admin_app.conductor'),
            preserve_default=False,
        ),
    ]
