# Generated by Django 5.1.4 on 2025-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0051_conductorscheduledbus_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbus',
            name='current_stop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
