# Generated by Django 5.1.4 on 2025-01-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0052_scheduledbus_current_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbus',
            name='stop_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
