# Generated by Django 5.1.4 on 2025-01-29 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0055_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
